### ISSUE TITLE
Add support to PHP 7

### ISSUE THREAD

**Issue by gwmoura** [tsuru/platforms#15]
We can create a php 7 support in tsuru php platform without create a new platform?

**Comment by jmjoly** [comment]
Indeed it would be nice to have PHP 7.0 and 7.1 support. It could be something like this:
php.interpretor.name = fpm70 or fpm71
Let me know if you want me to develop it and make a pull request.

But do you think "tsuru-made" platforms development (at least PHP) should be dropped, in favor of Heroku buildpacks? If so, the buildpack platform still needs an upgrade to support PHP 7.

**Comment by morpheu** [comment]
php platform now supports multi versions - including 7.0 and 7.1 versions
