### ISSUE TITLE
Python pip extra packages

### ISSUE THREAD

**Issue by daniloanp** [tsuru/platforms#29]
Doest Python platform support extra packages? I mean, the same behavior of call a "pip install "airflow[s3, postgres]""

**Comment by andrestc** [comment]
These need to be configured on your app using a `requirements.txt` or `setup.py`, those dependencies will be installed during the deploy.

**Comment by daniloanp** [comment]
Oh.. I just realize this is requirements.txt issue, not a Tsuru one.
