### ISSUE TITLE
clear_env not supported in PHP 5.5.9

### ISSUE THREAD

**Issue by jmjoly** [tsuru/platforms#31]
Hi,

I developed a simple PHP project running on Nginx and PHP-FPM (fpm55), but Tsuru couldn't start the container. After investigating, I realized the system (Ubuntu 14.04 LTS) installed PHP 5.5.9, however PHP-FPM 5.5.9 doesn't [support](http://php.net/manual/en/install.fpm.configuration.php) clear_env parameter (not until version 5.5.11) in pool.conf.

Do you think that clear_env parameter should be removed or at least commented so that a simple project wouldn't fail? Thank you.

Btw Tsuru is awesome!

**Comment by magnotorres** [comment]
The problem is that http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu no longer exists... we need to test the right location of it, may it helps: http://askubuntu.com/questions/741913/php7-0-dev-installation-fails-on-ubuntu-14-0-4/744382

**Comment by jmjoly** [comment]
Right, but that repository has already been changed to http://ppa.launchpad.net/ondrej/php/ubuntu, on November 10th 2016. It now installs PHP 5.5.9. Removing that clear_env parameter is actually a quick fix. The right thing to do would be dropping PHP 5.4 and 5.5 support (by the way the fpm54 interpreter also installs PHP 5.5.9), to have PHP 5.6, 7.0 and 7.1 supported (check other [issue](https://github.com/tsuru/platforms/issues/15)). What do you think Magno?

**Comment by magnotorres** [comment]
When you comment the clear_env parameter, wouldn't be anyway to use the environment tsuru send to the application (I agree its a quick fix, but it's not the way we want people experience php into tsuru). Updating the repository is the right way to go(we hope support php 7.0/7.1 too).

**Comment by morpheu** [comment]
@jmjoly we are right now working on php platform to support php versions 5.6 up to 7.1. When using php-fpm, clear_env is necessary to allow php receive envs, like service-instance injected variables. Today, php platform is broken and need to be fixed for php-fpm support.

**Comment by jmjoly** [comment]
Thank you all for your replies. And you're right, we should first fix PHP platform for versions 5.4 and 5.5, without losing environment variables. So I found 2 suitable ppa repositories respectively for php 5.4.45 and 5.5.34 (both support clear_env parameter in FPM configuration).

deb http://ppa.launchpad.net/ondrej/php5-oldstable/ubuntu precise main (https://launchpad.net/~ondrej/+archive/ubuntu/php5-oldstable)
deb http://ppa.launchpad.net/nickmoline/php55/ubuntu precise main (https://launchpad.net/~nickmoline/+archive/ubuntu/php55)

Those 2 repos can be directly added to PHP platform Dockerfile, besides the existing PHP repository. It should work fine even though we have to use "precise" instead of "trusty" version ("trusty" is not supported for those ppa's).

`apt-cache madison php5`
`php5 | 5.5.34+dfsg-1+deb.sury.org~precise+1 | http://ppa.launchpad.net/nickmoline/php55/ubuntu/ precise/main amd64 Packages`
`php5 | 5.5.9+dfsg-1ubuntu4.20 | http://archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages`
`php5 | 5.5.9+dfsg-1ubuntu4.20 | http://archive.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages`
`php5 | 5.5.9+dfsg-1ubuntu4 | http://archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages`
`php5 | 5.4.45-4+deprecated+dontuse+deb.sury.org~precise+1 | http://ppa.launchpad.net/ondrej/php5-oldstable/ubuntu/ precise/main amd64 Packages`

**Comment by morpheu** [comment]
@jmjoly we've updated php platform to support multi-versions (5.6, 7.0 and 7.1). Since 5.6 is a minimal version, it contemplate clear_env option. I tested all php versions and nginx+fpm seems to work with environment vars to me. Could you check it out ?

**Comment by jmjoly** [comment]
@morpheu Thank you so much for that amazing upgrade! For now, Nignx+FPM is not working... but I think it comes from the ownership of the FPM unix socket (the container doesn't actually start, I had to test manually):
`srw-rw---- 1 root root 0 Jan 31 14:35 /var/run/php/fpm.sock=`
Nginx log returns this error:
`connect() to unix:/var/run/php/fpm.sock failed (13: Permission denied) while connecting to upstream, client: 172.17.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/fpm.sock:"`

I saw that line was removed in a recent commit:
`os.system('chown -R %s /etc/php5/fpm /var/run/php5' % self.application.get('user'))`
Should FPM run as root?

In the case of Apache as a frontend of FPM, only Apache process is running, as the -D NO_DETACH option never returns the command line to execute FPM.

Everything else looks pretty good :) Thanks again!

**Comment by morpheu** [comment]
@jmjoly Could you provide me your tsuru.yaml php config section and steps you followed to update php platform cause I tested with Nginx+FPM and everything looks fine to me about socket permissions. Nginx is also running as defined user, which points to "ubuntu" user as below:

root        24  0.0  0.0  84352  1360 ?        Ss   12:59   0:00 nginx: master process /usr/sbin/nginx
ubuntu      25  0.0  0.1  84684  2288 ?        S    12:59   0:00 nginx: worker process
ubuntu      26  0.0  0.7 168448 16200 ?        Ss   12:59   0:00 php-fpm: master process (/etc/php/7.1/fpm/php-fpm.conf)
ubuntu      27  0.0  0.0  84684  2040 ?        S    12:59   0:00 nginx: worker process
ubuntu      28  0.0  0.0  84684  2040 ?        S    12:59   0:00 nginx: worker process
ubuntu      29  0.0  0.0  84684  2040 ?        S    12:59   0:00 nginx: worker process
ubuntu      30  0.0  0.2 168580  5240 ?        S    12:59   0:00 php-fpm: pool tsuru
ubuntu      31  0.0  0.2 168580  5108 ?        S    12:59   0:00 php-fpm: pool tsuru

The line that change socket and fpm permissions still remains in code:
https://github.com/tsuru/platforms/blob/master/php/interpretor.py#L52

About apache+fpm, I updated the platform and on next build it will fix apache running in foreground mode with FPM instead as daemon mode.

**Comment by jmjoly** [comment]
@morpheu I'm using a very simple hello world project to test tsuru PHP platform:
https://github.com/jmjoly/mytsuruphp.git

Now that you fixed the option in Apache, that frontend stopped working too, probably due to the FPM socket permissions. I could only check the permissions by setting a sleep in the Procfile, otherwise I'm unable to get a shell in the container:
`ubuntu@966843cbe844:/$ ls -al /var/run/php/`
`drwxr-xr-x  2 root root 4096 Jan 31 17:29 .`
`drwxr-xr-x 10 root root 4096 Jan 31 17:29 ..`

For every change you made, I deleted and downloaded the entire PHP platform, from Tsuru admin. For every deployment I did, I also deleted and recreated the PHP application, just to be sure :)

That type of project used to work in Tsuru. Is there something I should change? Thank you!

**Comment by morpheu** [comment]
@jmjoly I found and fixed the problem. I was creating /var/run/php after trying to change owner to proper user - which leads to "no such directory" always on first deploy after upgrade php image. On next build by docker hub will fix it. Thank you for all help on this issue :)

**Comment by jmjoly** [comment]
@morpheu Works great now!! Thanks again for helping and making quick change.
