### ISSUE TITLE
Ruby: warning message when specifying minor version

### ISSUE THREAD

**Issue by ggarnier** [tsuru/platforms#5]
After setting the Ruby version in my project as `2.2.3`, I started getting this warning message during deploy:

```
remote: WARNING: Invalid ruby version, please use 1.9.1, 1.9.3, 2.0, 2.1 or 2.2. Using ruby 2.2 as fallback.
remote: -- Using ruby version: 2.2.3 --
```

**Comment by gwmoura** [comment]
@fsouza we can use rvm or rbenv to solve this problem?
Another solution is compile ruby like heroku does. Ubuntu repositories are slow to update for new versions

What you think?

**Comment by fsouza** [comment]
@gwmoura I'm unfamiliar with Ruby on Heroku, I'm sorry. Does Heroku compile the language on demand? Or does it have a set of pre-compiled Rubies and then compiles on demand only when necessary?

**Comment by gwmoura** [comment]
@fsouza Heroku has a pre-compiled Rubies looks this [Dockerfile](https://github.com/heroku/docker-ruby/blob/master/Dockerfile#L13) for Heroku Docker.

When a new version is lauched, he compiles and stores on s3, Its more fast than compile on demand

**Comment by gwmoura** [comment]
@fsouza the PR #16 can close this issue?

**Comment by gwmoura** [comment]
@fsouza @andrewsmedina @ggarnier this issue can be closed?

**Comment by fsouza** [comment]
Yes, definitely.

@gwmoura thank you for working on that!

**Comment by gwmoura** [comment]
:wink:
