### ISSUE TITLE
Add support to pipenv

### ISSUE THREAD

**Issue by gwmoura** [tsuru/platforms#55]
Has the possibility to add support of `Pipfile` on python platform?

**Comment by lucasrodcosta** [comment]
Since today, Pipenv is the "officially recommended Python packaging tool from Python.org":
https://packaging.python.org/tutorials/managing-dependencies/
https://docs.pipenv.org/

It would be nice to have this support!

**Comment by cezarsa** [comment]
Fixed by #57
